### ISSUE TITLE
Extraction of values for AUC

### ISSUE THREAD

**Issue by bornexmachina** [nttcslab/dcase2023_task2_baseline_ae#3]
In networks/dcase2023t2_ae/dcase2023t2_ae.py around line 348 the extraction of AUC values begins
```
# extract scores for calculation of AUC (source) and AUC (target)
y_true_s_auc = [y_true[idx] for idx in range(len(y_true)) if domain_list[idx]=="source" or y_true[idx]==1]
y_pred_s_auc = [y_pred[idx] for idx in range(len(y_true)) if domain_list[idx]=="source" or y_true[idx]==1]
y_true_t_auc = [y_true[idx] for idx in range(len(y_true)) if domain_list[idx]=="target" or y_true[idx]==1]
y_pred_t_auc = [y_pred[idx] for idx in range(len(y_true)) if domain_list[idx]=="target" or y_true[idx]==1]
```
Why do you use or `y_true[idx]==1` ? It will be 1 for source as well as target. So here you mix up the scores.

Do I miss any key aspects?

**Comment by noboru2000** [comment]
Thank you for your comment, and sorry for this late reply.

The current implementation is correct and works as we intended.
DCASE 2022 and 2023 Challenge Task 2 are the domain generalization task.
Systems are required to detect whether the given sample is normal or an anomaly without knowing the domain of the given sample. A single threshold shall be assigned for source and target domains. This means that AUC shall be calculated using all the anomaly samples in both domains. AUC is a tradeoff curb showing detection accuracy when the threshold is set to a certain value represented by an anomaly sample.
